### PR TITLE
feat(#6): added files field to package.json template

### LINKED ISSUE #6: Suggestion: add "files" to the package.json template
- **Library Version**: code at b48b68a

Related: https://twitter.com/bitandbang/status/1088787376967700480

### PR DESCRIPTION
**Pull request by alemagio**
## Description

I didn't add the "index.js" because it should be added automatically since it is the main file ([npm doc](https://docs.npmjs.com/files/package.json#files))  

## Types of changes

Fixes #6 

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have updated the documentation (if required).
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] I added a picture of a cute animal cause it's fun

image

### CODE REVIEW

**Comment by alemagio** [comment]
Do you think I should add any test for this scenario?

**Comment by lirantal** [comment]
Nah, what bothered me was the superficial src/ directory and then `const app = require('./src)` felt weird because it's kind of determining something before the code is there.

That said, I think it's an overall ok to begin with as a skeleton.
Will merge away. Thanks @alemagio 🙏

**Comment by lirantal** [comment]
@alemagio looks like this PR broke a few things like it's not including rootDir files such as `.prettierrc.js` and others (travis, etc). Another small bug is that the require for 'src' should actually be a local reference: `require('./src')`.

Are you up to PRing the fixes?

**Comment by alemagio** [comment]
Sure
I'll push it asap
Sorry for the mistake

**Comment by lirantal** [comment]
No worries, I also didn't notice at first 😉

**Comment by lirantal** [comment]
Also, no rush if it's weekend time for you.

**Comment by alemagio** [comment]
I should have time this evening after work or tomorrow morning :wink:

**Comment by lirantal** [comment]
Sounds good :-)

**Comment by alemagio** [comment]
> @alemagio looks like this PR broke a few things like it's not including rootDir files such as `.prettierrc.js` and others (travis, etc)

I have a question about this.
I was reading the [npm doc](https://docs.npmjs.com/files/package.json#files) and, for what I understood, files like `.prettierrc.js` and `travis.yml` should not be included since those are for development. I would add SECURITY file maybe.
Please tell me if I'm wrong :sweat_smile:

**Comment by lirantal** [comment]
@alemagio You're correct and I know what's happening now.
Here is the tree view of the package published in the previous version that worked: https://unpkg.com/browse/create-node-lib@2.3.3/template/ and here it is with the new version introducing the change this PR: https://unpkg.com/browse/create-node-lib@2.4.0/template/

You can see that it was packaged without these files to begin with, and you're correct about not distributing them as well.

What I think we can do is the following:
1. Remove the `src` from package.json
2. Use this trick https://github.com/lirantal/create-node-lib/blob/master/saofile.js#L84-L93 to update the package.json with that src/ entry in files which will happen when the package is scaffolded

**Comment by alemagio** [comment]
Ok, got it.
It prevents those file to be in this package too, off course.
I'll fix it immediately.
Thanks for the explanation.

**Pull request merged**
